name: Test

on:
  push:
    branches: [ "feature/test-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          directory: ./pylint_sit
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          repository_username: __token__
#          repository_password: ${{ secrets.PYPI_TOKEN }}